apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gaor9i8pm-dotnet-basic
  janus-idp.io/tekton: gaor9i8pm-dotnet-basic
  backstage.io/kubernetes-id: gaor9i8pm-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gaor9i8pm-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
